name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "**"

env:
  AVALANCHE_TESTNET_URL: ${{ secrets.AVALANCHE_TESTNET_URL }}
  METAMASK_PRIVATE_KEY: ${{ secrets.METAMASK_PRIVATE_KEY }}
  ARBISCAN_API_KEY: ${{ secrets.ARBISCAN_API_KEY }}
  REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build -w packages/contracts
      - name: Pack contracts
        id: pack
        run: echo "tgz=$(npm pack -w packages/contracts | tail -n1)" >> $GITHUB_OUTPUT
      - name: Install packed contracts into app
        run: npm --prefix packages/app install ./${{ steps.pack.outputs.tgz }} --no-save --legacy-peer-deps
      - run: npm run build -w packages/app
      - run: npm test -w packages/app
